"""
Inject GitHub metadata and runtime environment variables into a notebook.

This script performs two actions:

1. Stores GitHub Actions metadata inside notebook metadata.
2. Inserts a hidden code cell at the top of the notebook that recreates
   required environment variables inside the Kaggle runtime.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

###############################################################################
# Notebook IO
###############################################################################


def load_notebook(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def save_notebook(notebook: dict, path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)


###############################################################################
# GitHub Metadata
###############################################################################


def github_metadata() -> dict[str, str]:
    """Collect GitHub Actions metadata."""

    return {
        "repository": os.getenv("GITHUB_REPOSITORY", ""),
        "workflow": os.getenv("GITHUB_WORKFLOW", ""),
        "sha": os.getenv("GITHUB_SHA", ""),
        "branch": os.getenv("GITHUB_REF_NAME", ""),
        "run_id": os.getenv("GITHUB_RUN_ID", ""),
        "run_number": os.getenv("GITHUB_RUN_NUMBER", ""),
        "actor": os.getenv("GITHUB_ACTOR", ""),
        "event": os.getenv("GITHUB_EVENT_NAME", ""),
    }


###############################################################################
# Environment Injection Cell
###############################################################################


def create_env_cell() -> dict:
    """Create hidden cell for Kaggle runtime."""

    lines = [
        "import os\n",
        "\n",
        "# Auto-generated by GitHub Actions\n",
        f'os.environ["DAGSHUB_USERNAME"] = "{os.getenv("DAGSHUB_USERNAME", "")}"\n',
        f'os.environ["DAGSHUB_TOKEN"] = "{os.getenv("DAGSHUB_TOKEN", "")}"\n',
        f'os.environ["KAGGLE_USER"] = "{os.getenv("KAGGLE_USERNAME", "")}"\n',
        f'os.environ["KAGGLE_DATASET_NAME"] = "{os.getenv("KAGGLE_DATASET_NAME", "")}"\n',
    ]

    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {
            "jupyter": {
                "source_hidden": True
            }
        },
        "outputs": [],
        "source": lines,
    }


###############################################################################
# Injection
###############################################################################


def inject_github_metadata(notebook: dict) -> dict:
    """Inject GitHub metadata into notebook metadata."""

    notebook.setdefault("metadata", {})
    notebook["metadata"]["github"] = github_metadata()

    return notebook


def inject_environment_cell(notebook: dict) -> dict:
    """Insert hidden environment variable cell."""

    notebook.setdefault("cells", [])

    notebook["cells"].insert(0, create_env_cell())

    return notebook


###############################################################################
# Main
###############################################################################


def main() -> None:
    notebook_path = Path(os.environ["NOTEBOOK"])

    notebook = load_notebook(notebook_path)

    notebook = inject_github_metadata(notebook)

    notebook = inject_environment_cell(notebook)

    save_notebook(notebook, notebook_path)

    print("Successfully injected GitHub metadata and runtime environment variables.")


if __name__ == "__main__":
    main()
